name: Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Docker image
        run: docker build -t remusing_cpp .

      - name: Run Docker image
        run: docker run --rm -i remusing_cpp < test/data/test.cpp
